# -*- coding: utf-8 -*-
"""Glucose-Insulin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ynqw1CPt6fgH2of0_oz-c_wHNqUAZZqI
"""

import numpy as np
from scipy.integrate import odeint,solve_ivp
import matplotlib.pyplot as plt
import math
import csv

def f(y, t, flag, params):

    b1 = 0.0059           # min^-1              # Insulin independent glucose utilization
    b2 = 0.1262           # min^-1              # Insulin disappearance rate
    b3 = 0.00005          # (pM * min)-1        # Insulin dependent glucose utilization
    b4 = 0.4543           # pM ∕ mM * min       # Glucose dependent insulin secretion
    b5 = 0.185            # min^-1              # Glucose transfer from liver to plasma
    b6 = 0.0102           # pM ∕ mmol * min     # Intestine glucose dependent incretin secretion
    b7 = 0.03             # min^-1              # Incretin disappearance rate
    b8 = 0.022            # min^-1              # Stomach glucose emptying rate
    b9 = 0.022            # min^-1              # Glucose transfer rate to the stomach
    b10 = 0.022           # min^-1              # Intestine glucose emptying rate
    b11 = 0.02            # min^-1              # Ghrelin disappearance
    b12 = 28.66           # pM ∕ min            # The appearance constant for ghrelin
    b13 = 0.0000095       # nM / mmol*min*kg    # Leptin secretion rate
    b14 = 0.0278          # min^-1              # Leptin disappearance
    b17 = 0.7             # mmol ∕ pM * min     # Ghrelin dependent glucose intake appearance
    b18 = 0.35            # nM^-1               # Leptin inhibition on glucose intake
    b19 = 0.004           # (mM * min)^-1       # Glucose effect rate on glucose intake
    b21 = 0.00876         # mmol ∕ min* pM      # Glucagon action on the liver
    b22 = 0.0021          # min^-1              # Glucose action on the liver
    b23 = 0.08            # mmol ∕ min          # Liver glucose constant production
    b25 = 0.00026         # mmol ∕ min* pM      # Insulin action on the liver
    b27 = 0.014           # min^-1              # Muscle glucose disappearance
    c = 0.1060            # (mM * min)^-1       # Incretin dependent insulin secretion
    c0 = 1.8854           # pM ∕ min            # Glucagon basal secretion
    c1 = 198              # (pM * nM ∕ min)     # Glucose action on Glucagon
    c2 = 94               # pM                  # Insullin action on glucagon
    c3 = 0.0554           # min^-1              # Glucagon disappearance
    e = 1.0               #  -                  # Insulin effectiveness
    Fat = 22.0            # kg                  # Averaged total fat mass in humans (kg)
    a1 = 0.9              # -                   # Fraction of absorbed glucose
    Gb = 5                # min(G)              # Fasting plasma glucose (Basal level; mM) calculated using min(G)
    Ge = 5.0              # mM                  # Glucose threshold value (mM)
    Ib = 46.5             # min(l)              # Fasting plasma insulin (Basal level; pM) calculated using min(I)
    k7a = 51              # min^-1              # Translocation of GLUT4 to the membrane (min^-1)
    k7b = 2290            # min^-1              # Translocation of GLUT4 to the cytosol (min^-1)
    k8 = 0.5275           # mmol/min            # GLUT4 glucose uptake (mmol/min)
    kmG1 = 1.082          # mg/kg               # Dependence on interstitial glucose saturated (mg/kg)
    kmG4 = 146.851        #  mg/kg              # Dependence on interstitial glucose saturated (mg/kg)
    l = 0.006             # mmol^-1             # Glucose in stomach dependent decay rate of ghrelin (mmol^-1)
    m = 0.04              # pM^-1               # Insulin dependent decay rate of ghrelin (pM^-1)
    p2U = 0.033           # min^-1              # Interstitial insulin rate of change (min^-1)
    q1 = 0.0031           # min^-1              # Interstitial glucose elimination rate (min^-1)
    q2 = 0.4054           # (mg/kg)/mM.min      # Glucose transger rate from plasma to interstitium ((mg/kg)/mM.min)
    r = 0.04              # pM^-1               # Insulin depdent decay rate of glucose intake (pM^-1)
    s = 0.03              # pM/min              # Incretin constant secretion (pM/min)
    v = 15                # liters              # Glucose distribution volume (liters)
    GLUT1 = 0.0283        # mmol/min            # GLUT1 glucose uptake (mmol/min)
    AS160_T642P = 43.4059 # ?                   # Substrate of PKB (phosphorylated)
    
    # Cortisol parameter
    kc2g = 0.0000214
 
    Si = y[0]       # (1) S = stomach gluose dynamics
    Di = y[1]       # (2) D = intestinal glucose dynamics
    Gi = y[2]       # (3) G = plasma glucose dynamics
    Ii = y[3]       # (4) I = insulin concentration
    Wi = y[4]       # (5) W = incretin concentration
    Ei = y[5]       # (6) E = glucagon concentration
    Li = y[6]       # (7) L = liver glucose dynamics
    Mi = y[7]       # (8) M = muscle glucose dynamics
    Ai = y[8]       # (9) A = adipose glucose dynamics 
    Yi = y[9]       # (10) Y = leptin concentration
    Qi = y[10]      # (11) Q = ghrelin concentration
    Hi = y[11]      # (12) H = glucose intake (hunger response)
    IIi = y[12]     # (13) II = interstitial insulin
    IGi = y[13]     # (14) IG = interstitial glucose
    G4mi = y[14]    # (15) G4m = membrane bound GLUT4
    G4i = y[15]     # (16) G4c = cytosolic GLUT4
    
    if flag == 0:
        cor = 0
    else:
        closest_index = params['index'].sub(t).abs().idxmin()
        cor = params.at[closest_index,'values']
    #print(cor)
    
    #Equations
    dSdt = b9*Hi - b8*Si

    dLdt = b8*Si - b10*Di

    dGdt = a1*((b10*Di)/v) + a1*((b5*Li)/v) - b1*Gi - b3*Ii*Gi         
    
    dIdt = b4*Gi + c*Wi*Gi - b2*Ii                                            
    
    dWdt = b6*Di - b7*Wi + s
    
    dEdt = c0 + (c1/(c2+Ii*e))*(Ge-Gi)*np.heaviside(Ge-Gi, 1) - c3*Ei
    
    dCdt = b23 - b25*Ii*e - b22*Gi + b21*Ei - b5*Li
    
    dMdt = 0.1*(v/a1)*b3*Gi*Ii*e - b27*Mi
    
    dAdt2 = k8*G4mi*(IGi/(kmG4+IGi)) + GLUT1*(IGi/(kmG1+IGi)) - 0.1*Ai 
    
    dYdt = b13*Ai*Fat - b14*Yi 
    
    dQdt = b12*math.exp(-l*Si)*math.exp(-m*Ii) - b11*Qi
    
    dHdt= (b17*Qi)/(b18*Yi + 1) * math.exp(-r*Ii) - b19*Gi*Hi - b9*Hi -kc2g*cor
    
    dINSdt = -p2U*IIi + p2U*(Ii-Ib)
    
    dGtdt = -q1*IGi + q2*(Gi-Gb)
    
    dGLUT4mdt = k7a*G4i*AS160_T642P - k7b*G4mi
    
    dGLUT4dt = -k7a*G4i*AS160_T642P + k7b*G4mi 
    
    return [dSdt, dLdt, dGdt, dIdt, dWdt, dEdt, dCdt, dMdt, dAdt2,
            dYdt, dQdt, dHdt, dINSdt, dGtdt, dGLUT4mdt, dGLUT4dt]

    
          
          
def Glucose_Insulin(flag,params):    
    
    #Initial Conditions of Each Equation
    Si = 4.0              # mmol     # Fasting stomach glucose
    Di = 14.0             # mmol     # Fasting intestine glucose
    Gi = 5.0              # mM       # Fasting plasma glucose
    Ii = 60.0             # pM       # Fasting plasma insulin
    Wi = 10.0             # pM       # Fasting plasma incretin
    Ei = 34.0             # pM       # Fasting plasma glucagon
    Li = 3.0              # mmol     # Fasting liver glucose
    Mi = 2.5              # mmol     # Fasting muscle glucose
    Ai = 53.19            # mmol     # Fasting intra-adipocitary glucose
    Yi = 0.4              # nM       # Fasting plasma leptin
    Qi = 120.0            # pM       # Fasting plasma ghrelin
    Hi = 200.0            # mmol     # Glucose intake
    IIi = 20.0            # pM       # Interstitial Insulin
    IGi = 135.0           # mg/kg    # Interstitial Glucose
    G4mi = 50.8472        # -        # Glucose transporter 4 in cytosol
    G4i = 49.1528         # -        # Glucose transporter 4 in membrane

    y0 = [Si, Di, Gi, Ii, Wi, Ei, Li, Mi, Ai, Yi, Qi, Hi, IIi, IGi, G4mi, G4i]

    #sim_time = 1440       #24 hours  #Total time of simulation in min 
    sim_time = 720        #14 hours  #Total time of simulation in min 
    deltaT = pow(10, -3)             # Step size
    t = np.arange(0,sim_time,deltaT)
    
    sol = odeint(f, y0, t, args=(flag,params))
    S = sol[:,0]
    D = sol[:,1]
    G = sol[:,2]
    I = sol[:,3]
    W = sol[:,4]
    E = sol[:,5]
    L = sol[:,6]
    M = sol[:,7]
    A = sol[:,8]
    Y = sol[:,9]
    Q = sol[:,10]
    H = sol[:,11]
    II = sol[:,12]
    IG = sol[:,13]
    G4m = sol[:,14]
    G4 = sol[:,15]
    
    outputs = [S, D, G, I, W, E, L, M, A, Y, Q, H, II, IG, G4m, G4]
    return [t, outputs]


def plot_GI(t, outputs, day):

    print(f'Glucose Dia: {day}')
    #if day == 1:
    [S, D, G, I, W, E, L, M, A, Y, Q, H, II, IG, G4m, G4] = outputs

    plt.figure()
    plt.plot(t, H, label="Glucose intake", linewidth=0.75) #/175
    plt.plot(t, S, label="Stomach glucose", linewidth=0.75) #135
    plt.plot(t, D, label="Intestinal glucose", linewidth=0.75) #125
    plt.plot(t, G, label="Plasma glucose", linewidth=0.75) #/20
    plt.plot(t, I, label="Insulin", linewidth=0.75) #/500
    plt.plot(t, W, label="Incretin", linewidth=0.75)
    plt.plot(t, E, label="Glucagon", linewidth=0.5)
    plt.plot(t, L, label="Liver glucose", linewidth=0.75) #*20
    plt.plot(t, M, label="Muscle glucose", linewidth=0.75) #*7.5
    #plt.plot(t, A, label="Adipose glucose")
    plt.plot(t, Y, label="Leptin", linewidth=0.75)
    plt.plot(t, Q/1.25, label="Ghrelin", linewidth=0.75)
    #plt.plot(t, II, label="Interstitial Insulin")
    #plt.plot(t, IG, label="Interstitial Glucose") #/700

    plt.xlabel("Time (min)")
    plt.ylabel("concentration (normalized)")    
    plt.legend(ncol = 3, loc='upper center',bbox_to_anchor = (0.5,-0.13),  fontsize = 11)
    plt.tight_layout()
    plt.savefig('Glucose Insulin.png')
    #else:
    #    print(f"Dia>1: {day}")
    #plt.show()


def save_output(folder,filename, outputs, day):
     ### create new file 
     nfilename = f'{folder}/{day}_'+filename
     f = open (nfilename, 'w')
     with open (nfilename, 'a') as f:
          writer = csv.writer(f)
          writer.writerow(outputs)  
          
          
             
#if __name__ == "__main__":
#     outputs = Glucose_Insulin()
  #   plot_GI(t, outputs)